from __future__ import annotations

from .models import Activity, Feedback, User, Venue


def load_users() -> list[User]:
    base_source = {
        "ntu_invite_claimed": True,
        "linkedin_style_certified": True,
        "ai_passport_imported": True,
        "self_input_completed": True,
        "redacted_by_user": True,
    }
    return [
        User(
            "u_001",
            "Fu-Syuan Wang",
            "NTU-FIRSTHOUR-001",
            True,
            True,
            True,
            True,
            "product",
            "consented LinkedIn verification / NTU invite candidate",
            "Product-minded builder interested in AI agents, social products, trust networks, matcha, thoughtful low-pressure conversation, and turning fuzzy user intent into usable product flows.",
            "low-medium",
            "thoughtful analytical product-oriented",
            ["AI agents", "matcha", "social products", "trust networks", "city walks"],
            ["AI agents", "offline social matching", "Taipei cafes"],
            ["loud bars", "forced networking", "pressure to exchange contacts"],
            "open_to_meet",
            ["Thu evening", "Sun afternoon"],
            800,
            1500,
            4,
            ["Da'an", "Xinyi", "Zhongshan"],
            ["public venue first", "mutual opt-in contact exchange"],
            "low",
            {"preferred_energy": "calm but lively", "recent_vibes": ["matcha", "ai-agents", "Da'an"]},
            {
                **base_source,
                "linkedin_profile_url": "https://www.linkedin.com/in/fu-syuan-wang-7719111a9/",
                "linkedin_usage": "consented verification/context handle only; no scraping",
                "profile_fields_source": "demo values from user-approved AI Passport and self input",
            },
        ),
        User(
            "u_002",
            "Ben",
            "NTU-FIRSTHOUR-002",
            True,
            True,
            True,
            True,
            "product",
            "NTU computer science alumni",
            "Product manager who likes AI tools, quiet cafes, future of work debates, design strategy, and reflective conversation.",
            "low-medium",
            "curious reflective structured",
            ["AI", "product strategy", "quiet cafes", "design", "bookstores"],
            ["AI tools", "career design", "urban life"],
            ["performative networking", "very loud venues"],
            "open_to_meet",
            ["Thu evening", "Sat afternoon"],
            700,
            1600,
            4,
            ["Da'an", "Xinyi", "Songshan"],
            ["public venue first", "no forced contact exchange"],
            "low",
            {"preferred_energy": "balanced", "recent_vibes": ["gallery", "product-ai", "Da'an"]},
            base_source.copy(),
        ),
        User(
            "u_003",
            "Celine",
            "NTU-FIRSTHOUR-003",
            True,
            True,
            True,
            True,
            "consulting",
            "NTU business alumni",
            "Strategy consultant curious about AI adoption, wine education, exhibits, and conversations that mix ambition with self-awareness.",
            "medium",
            "warm analytical direct",
            ["AI adoption", "wine", "exhibitions", "strategy", "founders"],
            ["future of work", "consumer behavior", "culture"],
            ["too quiet rooms", "unclear plans"],
            "serious_dating",
            ["Thu evening", "Sun afternoon"],
            1000,
            2200,
            4,
            ["Da'an", "Xinyi", "Zhongshan"],
            ["public venue first", "respect alcohol boundaries"],
            "medium",
            {"preferred_energy": "lively but respectful", "recent_vibes": ["wine", "consulting", "Xinyi"]},
            base_source.copy(),
        ),
        User(
            "u_004",
            "Daniel",
            "NTU-FIRSTHOUR-004",
            True,
            True,
            True,
            True,
            "startup",
            "NTU engineering alumni",
            "Founder type interested in AI agents, city walks, cafe work sessions, independent bookstores, and calm social settings.",
            "medium",
            "playful curious practical",
            ["AI agents", "startups", "city walks", "bookstores", "coffee"],
            ["AI agents", "building products", "Taipei neighborhoods"],
            ["formal dinners", "status games"],
            "open_to_meet",
            ["Thu evening", "Sat afternoon", "Sun afternoon"],
            600,
            1800,
            4,
            ["Da'an", "Zhongshan", "Songshan"],
            ["public venue first", "mutual opt-in contact exchange"],
            "low",
            {"preferred_energy": "curious and lightly energetic", "recent_vibes": ["bookstore", "startup-ai", "Zhongshan"]},
            base_source.copy(),
        ),
        User(
            "u_005",
            "Elaine",
            "NTU-FIRSTHOUR-005",
            True,
            True,
            True,
            True,
            "creative",
            "NTU design-adjacent alumni",
            "Brand strategist who enjoys gallery walks, scent workshops, visual culture, thoughtful food experiences, and warm small groups.",
            "medium",
            "observant warm aesthetic",
            ["gallery", "scent", "visual culture", "food", "city walks"],
            ["culture", "brand", "taste"],
            ["tech-only talk", "interview-style dinners"],
            "friendship_first",
            ["Sat afternoon", "Sun afternoon"],
            900,
            1800,
            4,
            ["Zhongshan", "Da'an", "Xinyi"],
            ["public venue first", "no pressure to share socials"],
            "low",
            {"preferred_energy": "warm and balanced", "recent_vibes": ["gallery", "creative", "Zhongshan"]},
            base_source.copy(),
        ),
        User(
            "u_006",
            "Frank",
            "NTU-FIRSTHOUR-006",
            True,
            True,
            True,
            True,
            "finance",
            "NTU economics alumni",
            "Investment analyst interested in AI market structure, coffee, wine, macro conversations, and low-pressure after-work plans.",
            "low-medium",
            "analytical dry-humor calm",
            ["AI markets", "coffee", "wine", "macro", "career transitions"],
            ["AI in finance", "markets", "Taipei cafes"],
            ["crowded clubs", "forced intimacy"],
            "open_to_meet",
            ["Thu evening", "Fri evening"],
            900,
            2000,
            4,
            ["Da'an", "Xinyi"],
            ["public venue first", "mutual opt-in contact exchange"],
            "medium",
            {"preferred_energy": "calm but not sleepy", "recent_vibes": ["wine", "finance-ai", "Xinyi"]},
            base_source.copy(),
        ),
        User(
            "u_007",
            "Grace",
            "NTU-FIRSTHOUR-007",
            True,
            True,
            True,
            True,
            "tech",
            "NTU CS student",
            "Graduate student exploring AI safety, Computex, bookstores, matcha, and conversations that do not feel like networking.",
            "low",
            "reflective precise gentle",
            ["AI safety", "Computex", "bookstores", "matcha", "research"],
            ["AI safety", "research culture", "future of work"],
            ["loud bars", "being pressured for contact"],
            "open_to_meet",
            ["Thu evening", "Sun afternoon"],
            500,
            1400,
            4,
            ["Da'an", "Gongguan", "Zhongshan"],
            ["public venue first", "mutual opt-in contact exchange"],
            "none",
            {"preferred_energy": "quiet but engaged", "recent_vibes": ["bookstore", "AI research", "Gongguan"]},
            base_source.copy(),
        ),
        User(
            "u_008",
            "Hannah",
            "NTU-FIRSTHOUR-008",
            True,
            True,
            True,
            True,
            "medicine",
            "NTU medicine alumni",
            "Doctor interested in wellness, pottery, quiet dinners, healthcare AI, and sincere conversations with emotionally steady people.",
            "low-medium",
            "gentle sincere grounded",
            ["wellness", "pottery", "healthcare AI", "quiet dinner", "tea"],
            ["healthcare AI", "burnout", "daily rituals"],
            ["alcohol-heavy events", "competitive networking"],
            "serious_dating",
            ["Sun afternoon", "Fri evening"],
            800,
            1700,
            4,
            ["Da'an", "Zhongshan"],
            ["public venue first", "respect alcohol boundaries"],
            "none",
            {"preferred_energy": "calm and sincere", "recent_vibes": ["pottery", "wellness", "Zhongshan"]},
            base_source.copy(),
        ),
        User(
            "u_009",
            "Ian",
            "NTU-FIRSTHOUR-009",
            True,
            True,
            True,
            True,
            "product",
            "NTU MBA alumni",
            "MBA operator interested in AI productivity, career pivots, matcha, wine, and honest conversations about ambition without posturing.",
            "medium",
            "warm strategic open",
            ["AI productivity", "career pivots", "matcha", "wine", "MBA"],
            ["career pivots", "AI at work", "ambition"],
            ["status games", "very quiet rooms"],
            "open_to_meet",
            ["Thu evening", "Sun afternoon"],
            900,
            1800,
            4,
            ["Da'an", "Xinyi", "Zhongshan"],
            ["public venue first", "mutual opt-in contact exchange"],
            "medium",
            {"preferred_energy": "balanced with momentum", "recent_vibes": ["matcha", "MBA", "Da'an"]},
            base_source.copy(),
        ),
        User(
            "u_010",
            "Jasmine",
            "NTU-FIRSTHOUR-010",
            True,
            True,
            True,
            True,
            "law",
            "NTU law alumni",
            "Lawyer interested in privacy, art spaces, bookstores, structured self-disclosure, and respectful low-pressure dating.",
            "low-medium",
            "thoughtful precise warm",
            ["privacy", "art", "bookstores", "structured conversation", "tea"],
            ["privacy", "trust", "city culture"],
            ["oversharing too fast", "unclear boundaries"],
            "serious_dating",
            ["Thu evening", "Sat afternoon"],
            800,
            1600,
            4,
            ["Da'an", "Zhongshan"],
            ["public venue first", "clear contact boundaries"],
            "low",
            {"preferred_energy": "thoughtful and safe", "recent_vibes": ["gallery", "privacy", "Zhongshan"]},
            base_source.copy(),
        ),
        User(
            "u_011",
            "Kai",
            "NTU-FIRSTHOUR-011",
            True,
            True,
            True,
            True,
            "consulting",
            "NTU alumni / strategy",
            "Consultant interested in tech expos, AI transformation, cocktail craft, career ambition, and energetic but respectful groups.",
            "medium-high",
            "direct lively curious",
            ["Computex", "AI transformation", "cocktails", "career ambition", "strategy"],
            ["AI transformation", "industry shifts", "career choices"],
            ["overly quiet rooms", "unstructured hangouts"],
            "open_to_meet",
            ["Fri evening", "Sat afternoon"],
            1000,
            2200,
            4,
            ["Xinyi", "Songshan", "Zhongshan"],
            ["public venue first", "respect alcohol boundaries"],
            "medium",
            {"preferred_energy": "energetic but respectful", "recent_vibes": ["Computex", "consulting", "Xinyi"]},
            base_source.copy(),
        ),
        User(
            "u_012",
            "Lina",
            "NTU-FIRSTHOUR-012",
            True,
            True,
            True,
            True,
            "data",
            "NTU statistics alumni",
            "Data scientist interested in recommender systems, matcha, galleries, urban walks, and conversations that connect technical ideas to daily life.",
            "low-medium",
            "curious precise relaxed",
            ["recommender systems", "matcha", "galleries", "urban walks", "AI"],
            ["recommendation systems", "AI in life", "city design"],
            ["loud bars", "forced dating energy"],
            "open_to_meet",
            ["Thu evening", "Sun afternoon"],
            700,
            1500,
            4,
            ["Da'an", "Zhongshan", "Gongguan"],
            ["public venue first", "mutual opt-in contact exchange"],
            "low",
            {"preferred_energy": "calm curious", "recent_vibes": ["gallery", "AI", "Zhongshan"]},
            base_source.copy(),
        ),
    ]


def load_activities() -> list[Activity]:
    return [
        Activity("a_001", "Matcha tasting + cafe debrief", "matcha", ["shared object", "low pressure", "quiet", "structured"], ["low", "low-medium", "medium"], 0.12, "medium", "none", 600, 1400, 90, [3, 4, 5], "matcha tasting quiet cafe shared object thoughtful low pressure first meeting"),
        Activity("a_002", "Gallery walk + tea", "gallery", ["movement", "visual prompts", "low pressure", "public"], ["low", "low-medium", "medium"], 0.14, "medium", "none", 500, 1500, 120, [3, 4, 5], "gallery walk art visual culture tea movement low pressure public"),
        Activity("a_003", "Computex walk + cafe debrief", "expo", ["shared observation", "movement", "topic-rich", "public"], ["low-medium", "medium", "medium-high"], 0.18, "low", "none", 500, 1600, 150, [3, 4, 5], "Computex technology expo AI startups shared observation cafe debrief"),
        Activity("a_004", "Wine tasting table", "wine", ["structured", "ritual", "dating signal", "sensory"], ["medium", "medium-high"], 0.34, "high", "medium", 1200, 2400, 90, [3, 4], "wine tasting sensory structured dating signal higher intimacy"),
        Activity("a_005", "Bookstore browse + coffee", "bookstore", ["movement", "quiet", "conversation prompts", "low pressure"], ["low", "low-medium"], 0.10, "medium", "none", 400, 1200, 90, [3, 4], "bookstore coffee quiet reflective conversation prompts low pressure"),
        Activity("a_006", "Pottery mini-workshop", "pottery", ["hands-on", "introvert-friendly", "shared task", "low pressure"], ["low", "low-medium", "medium"], 0.15, "medium", "none", 1000, 2200, 120, [3, 4, 5], "pottery workshop hands on introvert friendly shared task"),
        Activity("a_007", "Scent design workshop", "scent", ["sensory", "structured", "aesthetic", "shared task"], ["low-medium", "medium"], 0.16, "medium", "none", 1100, 2200, 120, [3, 4], "scent design workshop sensory aesthetic structured warm small group"),
        Activity("a_008", "Cocktail craft session", "cocktail", ["lively", "sensory", "dating signal", "structured"], ["medium", "medium-high"], 0.38, "high", "medium", 1300, 2600, 100, [3, 4], "cocktail craft lively sensory structured higher energy dating signal"),
    ]


def load_venues() -> list[Venue]:
    return [
        Venue("v_001", "Hikari Matcha Room", "Da'an", "cafe", 3, 6, ["Thu evening", "Sun afternoon"], 980, True, "quiet", "medium", False, 0.92, ["matcha", "quiet", "public", "thoughtful"], ["matcha"], "quiet matcha cafe Da'an public thoughtful first meeting"),
        Venue("v_002", "Zhongshan Gallery Tea Bar", "Zhongshan", "gallery cafe", 3, 8, ["Sat afternoon", "Sun afternoon"], 900, True, "moderate", "medium", False, 0.90, ["gallery", "tea", "public", "aesthetic"], ["gallery"], "gallery tea Zhongshan visual culture public movement"),
        Venue("v_003", "Future Hall Expo Lounge", "Xinyi", "expo cafe", 4, 8, ["Sat afternoon"], 1200, True, "moderate", "low", False, 0.84, ["tech", "expo", "AI", "public"], ["expo"], "Computex expo lounge Xinyi technology AI public cafe"),
        Venue("v_004", "Quiet Shelf Cafe", "Da'an", "bookstore cafe", 3, 5, ["Thu evening", "Sat afternoon"], 750, True, "quiet", "medium", False, 0.88, ["bookstore", "coffee", "quiet", "reflective"], ["bookstore"], "bookstore cafe Da'an quiet reflective coffee"),
        Venue("v_005", "Clay Studio Zhongshan", "Zhongshan", "workshop studio", 3, 6, ["Sun afternoon"], 1500, True, "moderate", "medium", False, 0.87, ["pottery", "hands-on", "warm"], ["pottery"], "pottery workshop Zhongshan hands on calm public studio"),
        Venue("v_006", "Scent Lab Da'an", "Da'an", "workshop studio", 3, 5, ["Thu evening", "Sun afternoon"], 1600, True, "quiet", "medium", False, 0.86, ["scent", "aesthetic", "structured"], ["scent"], "scent design workshop Da'an quiet aesthetic structured"),
        Venue("v_007", "Cellar 23", "Xinyi", "wine bar", 3, 5, ["Thu evening", "Fri evening"], 1800, True, "moderate", "high", True, 0.89, ["wine", "sensory", "dating signal"], ["wine"], "wine tasting Xinyi structured sensory public bar"),
        Venue("v_008", "Signal Cocktail Lab", "Songshan", "cocktail bar", 3, 5, ["Fri evening", "Sat afternoon"], 1900, True, "loud", "high", True, 0.80, ["cocktail", "lively", "sensory"], ["cocktail"], "cocktail craft Songshan lively louder structured"),
    ]


def load_feedback() -> list[Feedback]:
    examples = [
        ("u_001", True, .92, .88, .82, True, True, "balanced", "slightly more energetic next time", "Conversation around AI at work felt natural, but the room was a little too quiet."),
        ("u_002", True, .88, .84, .90, False, True, "balanced", "similar energy", "Gallery prompts worked well and reduced interview feeling."),
        ("u_003", True, .76, .70, .64, True, True, "too quiet", "more lively", "Wanted more momentum and a clearer dating signal."),
        ("u_004", True, .86, .80, .78, False, True, "balanced", "more builders", "Liked practical builders and low status energy."),
        ("u_005", True, .82, .86, .92, False, True, "balanced", "more creative venues", "Aesthetic setting helped conversation."),
        ("u_006", True, .72, .70, .68, False, True, "too formal", "less dinner-coded", "Wine was fine but felt more formal than desired."),
        ("u_007", True, .90, .88, .86, False, True, "calm", "similar but slightly warmer", "Bookstore activity felt safe and easy."),
        ("u_008", True, .84, .82, .94, False, True, "calm", "same people type", "Hands-on activity made conversation less intense."),
        ("u_009", True, .78, .80, .72, True, True, "too quiet", "more energetic", "Wanted a bit more energy after the first half."),
        ("u_010", True, .88, .84, .86, False, True, "balanced", "similar safety clarity", "Clear boundaries increased comfort."),
        ("u_011", True, .80, .78, .70, True, True, "too quiet", "higher energy", "Expo worked, cafe was too quiet."),
        ("u_012", True, .91, .89, .88, False, True, "calm", "same topic cluster", "Loved technical ideas connected to daily life."),
    ]
    extra = [
        ("u_001", True, .80, .78, .60, False, True, "too quiet", "try gallery walk", "Another cafe felt repetitive."),
        ("u_002", True, .74, .70, .68, False, True, "too intense", "lower pressure", "Cocktail energy was too high."),
        ("u_003", False, .00, .00, .00, False, True, "n/a", "better time", "Schedule conflict, did not attend."),
        ("u_004", True, .79, .82, .76, True, True, "balanced", "more AI operators", "Good practical energy."),
        ("u_005", True, .69, .72, .58, False, True, "too technical", "more culture mix", "Tech-only talk was too narrow."),
        ("u_006", True, .83, .78, .75, True, True, "balanced", "similar finance-ai cluster", "Liked finance AI topics."),
        ("u_010", True, .90, .87, .82, False, True, "balanced", "more privacy/trust topics", "Trust topic led to good conversation."),
        ("u_012", True, .76, .78, .70, False, True, "too repetitive", "new activity", "Matcha again felt predictable."),
    ]
    return [Feedback(*row) for row in examples + extra]
